=== EPISTON/cursusrncp/javaxml/xmljavaschemaForm/repertoire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://courtalon.com/repertoire"
		xmlns:tns="http://courtalon.com/repertoire" elementFormDefault="qualified">

	<element name="repertoire">
		<complexType>
			<sequence>
				<element name="entree" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="nom" type="string" />
							<element name="prenom" type="string" />
						</sequence>
						<attribute name="no" type="integer" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== EPISTON/cursusrncp/javaxml/xmljavaschemaForm/repertoire.xml
<?xml version="1.0" encoding="UTF-8"?>
<repertoire xmlns="http://courtalon.com/repertoire"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://courtalon.com/repertoire repertoire.xsd" >
  <entree no="1">
    <nom>Courtalon</nom>
    <prenom>Vincent</prenom>
  </entree>
  <entree no="2">
    <nom>Bob</nom>
    <prenom>Joe</prenom>
  </entree>
  <entree no="3">
    <nom>Bohn</nom>
    <prenom>bobby</prenom>
  </entree>
   
</repertoire>
